CREATE TABLE Vendas (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_venda DATE NOT NULL,
    valor_total NUMBER(10, 2) NOT NULL,
    id_produto NUMBER,
    CONSTRAINT fk_produto
        FOREIGN KEY (id_produto)
        REFERENCES Produto(id)
);
